version: "3.9"
services:
  web:
    image: juanjoseguevara/server-web-web
    working_dir: "/uh-management-console/uh-web-client"
    networks:
      - uh-integration
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_ANONYMOUS_ACCESS_ENABLED=true
      - REACT_APP_DASHBOARD_URI=http://localhost:3001/d-solo/ERNvb7o4k/ultihash-monitoring
      - REACT_APP_DASHBOARD_PANEL_IDS=[4, 2]
  grafana:
    image: grafana/grafana-enterprise
    networks:
      - uh-integration
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - type: bind
        source: /data/grafana/
        target: /var/lib/grafana
  prometheus:
    image: prom/prometheus
    networks:
      - uh-integration
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: /data/prometheus
        target: /prometheus
  pushgateway:
    image: prom/pushgateway
    networks:
      - uh-integration
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
  uh-server-db:
    image: ghcr.io/ultihash/server-db:20230503
    networks:
      - uh-integration
    ports:
      - target: 21832
        published: 21832
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == database
    volumes:
      - type: bind
        source: /mnt/disk1/uh-data-node
        target: /var/lib/uh-data-node
  uh-server-agency:
    image: ghcr.io/ultihash/server-agency:20230503
    networks:
      - uh-integration
    ports:
      - target: 21832
        published: 21833
        protocol: tcp
        mode: host
      - target: 8080
        published: 8090
        protocol: tcp
        mode: host
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
    volumes:
      - type: bind
        source: /data/uh-agency-node
        target: /var/lib/uh-agency-node
  uh-client-shell:
    image: ghcr.io/ultihash/client-shell:20230503
    networks:
      - uh-integration
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.role == agency
networks:
  uh-integration:
    driver: overlay
