version: "3.9"
services:
  web:
    image: juanjoseguevara/server-web-web
    working_dir: "/uh-management-console/uh-web-client"
    networks:
      - uh-integration
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == agency
    environment:
    - WATCHPACK_POLLING=true
    - REACT_APP_ANONYMOUS_ACCESS_ENABLED=true
    - REACT_APP_DASHBOARD_URI=http://localhost:3001/d-solo/ERNvb7o4k/ultihash-monitoring
    - REACT_APP_DASHBOARD_PANEL_IDS=[4, 2]
  grafana:
    image: grafana/grafana-enterprise
    networks:
      - uh-integration
    ports:
      - "3001:3000"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == agency
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-storage:/var/lib/grafana grafana/grafana-enterprise
  prometheus:
    image: prom/prometheus
    networks:
      - uh-integration
    ports: 
      - "9091:9090"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == agency
    volumes: 
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
  uh-server-db:
    image: ghcr.io/ultihash/server-db:20230302
    networks:
      - uh-integration
    deploy:
      mode: replicated
      replicas: 1
      placement:
         constraints:
          - node.labels.role == database
  uh-server-agency:
    image: ghcr.io/ultihash/server-agency:20230302
    networks:
      - uh-integration
    ports:
      - "21832:21832"
    deploy: 
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == agency
  uh-client-shell:
    image: ghcr.io/ultihash/client-shell:20230302
    networks:
      - uh-integration
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.role == agency
volumes:
  grafana-storage:
networks:
  uh-integration:
    driver: overlay
