version: "3.9"
services:
  uh-server-db:
    image: uh-server-db
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_SERVER_DB
        - SRC_PATH=server-db
        - TARGET=uh-data-node
  uh-server-agency:
    image: uh-server-agency
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_SERVER_AGENCY
        - SRC_PATH=server-agency
        - TARGET=uh-agency-node
    ports:
      - "21832:21832"
    depends_on:
      - uh-server-db
    links:
      - uh-server-db
  uh-client-shell:
    image: uh-client-shell
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - CMAKE_OPTION=BUILD_CLIENT_SHELL
        - SRC_PATH=client-shell
        - TARGET=uh-cli
    ports:
      - "1337:1337/udp"
    depends_on:
      - uh-server-db
      - uh-server-agency
    links:
      - uh-server-agency