#!/bin/bash

#
# Help text
#
usage () {
    echo "usage: chk_license.sh [--key <path>] <license file>"
    echo
    echo "<license file>    - UH license file"
    echo "--key <path>      - path to the public key file as generated by mk_keys.sh"
}

#
# Command line parsing
#
public_key_file="uh-license-public.key"
license_file=""

while [ -n "$1" ]; do

    case "$1" in
        --key)
                public_key_file="$2"
                shift
                ;;
        *)
                license_file="$1"
                ;;
    esac

    shift
done

[ -z "$license_file" ] && { usage; exit 1; }
[ -f "$license_file" ] || { echo "cannot read $license_file"; exit 1; }
[ -f "$public_key_file" ] || { echo "cannot read $public_key_file"; exit 1; }

#
# Perform action
#
tmp_file_sign=$(mktemp)
grep --only-matching --extended-regexp '[^:]+$' $license_file | base64 --decode > $tmp_file_sign

tmp_file_license=$(mktemp)
grep --only-matching --extended-regexp '^(.*:)+' $license_file | sed 's/:$//' | tr --delete '\n' > $tmp_file_license

if ! openssl pkeyutl -verify -pubin -inkey $public_key_file -rawin -in $tmp_file_license -sigfile $tmp_file_sign; then
    echo "The file is not a valid license file!"
    rm $tmp_file_license $tmp_file_sign
    exit 1
fi

echo
echo "The given license file $license_file contains following fields:"
echo "customer id:       $(cut --delimiter ':' --fields=1 $tmp_file_license)"
echo "max storage size:  $(cut --delimiter ':' --fields=2 $tmp_file_license) GB"

rm $tmp_file_license $tmp_file_sign
