#!/bin/bash

#
# Help text
#
usage () {
    echo "usage: mk_license.sh [--key <path>] <customer id> <storage limit>"
    echo
    echo "--key <path>    - path to private key file as generated by mk_keys.sh"
    echo "<customer id>   - string to identify the customer"
    echo "<storage limit> - maximum amount of data in directory in GB"
}

#
# Command line parsing
#
private_key_file="uh-license-private.key"

while [ -n "$1" ]; do

    case "$1" in
        --key)
                private_key_file="$2"
                shift
                ;;
        *)      break
    esac

    shift
done

customer_id="$1"
storage_limit="$2"

[ -n "$storage_limit" ] || { usage; exit 1; }
[ -f "$private_key_file" ] || { echo "cannot open $private_key_file"; exit 1; }

#
# Perform action
#
license="${customer_id}:${storage_limit}"

tmp_file_license=$(mktemp)
echo -n $license > $tmp_file_license

tmp_file_sign=$(mktemp)
if openssl pkeyutl -sign -inkey $private_key_file -out $tmp_file_sign -rawin -in $tmp_file_license; then
    license_file="${customer_id}-$(date +%Y%m%d-%H%M%S).lic"
    echo "$license:$(base64 --wrap=0 $tmp_file_sign)" > $license_file
    echo "license file can be found under $license_file"
else
    echo "generation of license file failed"
fi

rm $tmp_file_license $tmp_file_sign
