name: Nightly Docker Build

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu1804, ubuntu2004, ubuntu2204 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          export IMAGE_TAG=lib-common:${{ matrix.os }}-$(date +%Y%m%d%H%M%S)
          docker build . --file Dockerfile.${{ matrix.os }} --tag $IMAGE_TAG
          docker run --rm -t $IMAGE_TAG