global:
  image: $CORE_IMAGE
  imagePullPolicy: Always
  imagePullSecrets:               
    - registry-credentials
  ultihashSecret:
    name: ultihash
    key: license
  logLevel: DEBUG
  telemetryExportInterval: 30000
  securityContext:
    capabilities:
      add:
      - SYS_PTRACE

etcd:
  replicaCount: 1
  nodeSelector:
    workload-type: directory
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  persistence:
    size: 8Gi
    storageClass: local-path

entrypoint:
  replicas: 2
  nodeSelector:
    workload-type: entrypoint
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - entrypoint
        topologyKey: kubernetes.io/hostname 

  ingress:
    enabled: false

storage:
  replicas: 2
  storageClass: local-path          
  storageSize: 70Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - storage
        topologyKey: kubernetes.io/hostname                  
  nodeSelector:
    workload-type: storage
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

deduplicator:
  replicas: 2
  storageClass: local-path
  storageSize: 10Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - deduplicator
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    workload-type: storage
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

database:
  primary:
    nodeSelector:
      workload-type: directory
      purpose: performance-testing-small
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

    persistence:
      storageClass: local-path
      size: 20Gi

databaseInit:
  image: $DATABASE_INIT_IMAGE
  nodeSelector:
    workload-type: directory
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

collector:
  nodeSelector:
    purpose: performance-testing-small
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  extraEnvs:
  - name: UH_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: UH_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UH_EXPORTER_TOKEN
    valueFrom:
      secretKeyRef:
        name: ultihash
        key: token
  presets:
    kubeletMetrics:              
      enabled: false           
  config:                         
    exporters:
      otlphttp/uptrace:
        endpoint: http://uptrace-backend.uptrace.svc.cluster.local:14318
        headers:
          uptrace-dsn: http://${env:UH_EXPORTER_TOKEN}@uptrace-backend.uptrace.svc.cluster.local:14318
    receivers:
      prometheus: null
      kubeletstats: null
    service:
      pipelines:
        metrics:
          receivers:
            - otlp

exporter:
  enabled: false
                   