version: '3'

services:
    etcd:
        image: bitnami/etcd
        container_name: etcd
        environment:
            - ALLOW_NONE_AUTHENTICATION=yes
        healthcheck:
            test: etcdctl endpoint health

    deduplicator:
        image: uh-cluster:testing
        container_name: dedupe
        restart: always
        environment:
            - UH_LICENSE=${UH_LICENSE}
        entrypoint: [ "uh-cluster", "--registry", "etcd:2379", "deduplicator" ]
        healthcheck:
            test: [ "CMD", "lsof", "-i", "TCP:9300" ]
            timeout: 1s
            interval: 5s
            retries: 5
        depends_on:
            etcd:
                condition: service_healthy

    storage:
        image: uh-cluster:testing
        container_name: data
        restart: always
        environment:
            - UH_LICENSE=${UH_LICENSE}
        entrypoint: [ "uh-cluster", "--registry", "etcd:2379", "storage" ]
        healthcheck:
            test: [ "CMD", "lsof", "-i", "TCP:9200" ]
            timeout: 1s
            interval: 5s
            retries: 5
        depends_on:
            etcd:
                condition: service_healthy

    directory:
        image: uh-cluster:testing
        container_name: directory
        restart: always
        environment:
            - UH_LICENSE=${UH_LICENSE}
        entrypoint: [ "uh-cluster", "--registry", "etcd:2379", "directory" ]
        healthcheck:
            test: [ "CMD", "lsof", "-i", "TCP:9400" ]
            timeout: 1s
            interval: 5s
            retries: 5
        depends_on:
            etcd:
                condition: service_healthy

    entrypoint:
        image: uh-cluster:testing
        container_name: entrypoint
        restart: always
        environment:
            - UH_LICENSE=${UH_LICENSE}
        entrypoint: [ "uh-cluster", "--registry", "etcd:2379", "entrypoint" ]
        depends_on:
            etcd:
                condition: service_healthy
            deduplicator:
                condition: service_healthy
            storage:
                condition: service_healthy
            directory:
                condition: service_healthy
        ports:
            - "8080:8080"
