global:
  image: $CORE_IMAGE
  imagePullPolicy: Always
  imagePullSecrets:               
    - registry-credentials
  ultihashSecret:
    name: ultihash
    key: license
  logLevel: DEBUG
  telemetryExportInterval: 30000
  securityContext:
    capabilities:
      add:
      - SYS_PTRACE

stabilityTest:
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01
  inputVolume:
    type: hostPath
    mountPath: /data
    hostPath: /data/corpora_test/stability-test
  outputVolume:
    pvcName: stability-test-output
    mountPath: /testing/test

etcd:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01
  persistence:
    size: 5Gi
    storageClass: local-path

entrypoint:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01

  ingress:
    enabled: false

storage:
  replicas: 2
  storageClass: local-path            
  storageSize: 50Gi                  
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01

deduplicator:
  replicas: 2
  storageClass: local-path
  storageSize: 4Gi
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01

database:
  primary:
    nodeSelector:
      kubernetes.io/hostname: opm-k8s-worker-01

    persistence:
      storageClass: local-path
      size: 4Gi

databaseInit:
  image: $DATABASE_INIT_IMAGE

collector:
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-01
  extraEnvs:
  - name: UH_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: UH_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UH_EXPORTER_TOKEN
    valueFrom:
      secretKeyRef:
        name: ultihash
        key: token
  presets:
    kubeletMetrics:              
      enabled: false           
  config:                         
    exporters:
      otlphttp/uptrace:
        endpoint: http://opm-k8s-worker-04.ultihash.io
        headers:
          uptrace-dsn: http://${env:UH_EXPORTER_TOKEN}@opm-k8s-worker-04.ultihash.io
    receivers:
      prometheus: null
      kubeletstats: null
    service:
      pipelines:
        metrics:
          receivers:
            - otlp

exporter:
  enabled: false
