global:
  image: $CORE_IMAGE
  imagePullPolicy: Always
  imagePullSecrets:               
    - registry-credentials
  ultihashSecret:
    name: ultihash
    key: license
  logLevel: DEBUG
  telemetryExportInterval: 30000
  securityContext:
    capabilities:
      add:
      - SYS_PTRACE

stabilityTest:
  readTimeout: 9999
  concurentJobs: 4
  nodeSelector:
    workload-type: entrypoint
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  inputVolume:
    type: S3
    mountPath: /data
    pvcName: stability-test-input
  outputVolume:
    pvcName: stability-test-output
    mountPath: /testing/test

etcd:
  replicaCount: 1
  nodeSelector:
    workload-type: entrypoint
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  persistence:
    size: 5Gi
    storageClass: ebs-csi-gp3

entrypoint:
  replicas: 1
  nodeSelector:
    workload-type: entrypoint
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

  ingress:
    enabled: false

storage:
  replicas: 2
  storageClass: ebs-csi-gp3            
  storageSize: 50Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - storage
        topologyKey: kubernetes.io/hostname                  
  nodeSelector:
    workload-type: storage
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

deduplicator:
  replicas: 2
  storageClass: ebs-csi-gp3
  storageSize: 4Gi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - deduplicator
        topologyKey: kubernetes.io/hostname
  nodeSelector:
    workload-type: storage
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

database:
  primary:
    nodeSelector:
      workload-type: directory
      purpose: performance-and-stability-testing
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"

    persistence:
      storageClass: ebs-csi-gp3
      size: 4Gi

databaseInit:
  image: $DATABASE_INIT_IMAGE

collector:
  nodeSelector:
    purpose: performance-and-stability-testing
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  extraEnvs:
  - name: UH_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: UH_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UH_EXPORTER_TOKEN
    valueFrom:
      secretKeyRef:
        name: ultihash
        key: token
  presets:
    kubeletMetrics:              
      enabled: false           
  config:                         
    exporters:
      otlphttp/uptrace:
        endpoint: http://uptrace-backend.uptrace.svc.cluster.local:14318
        headers:
          uptrace-dsn: http://${env:UH_EXPORTER_TOKEN}@uptrace-backend.uptrace.svc.cluster.local:14318
    receivers:
      prometheus: null
      kubeletstats: null
    service:
      pipelines:
        metrics:
          receivers:
            - otlp

exporter:
  enabled: false
                   