global:
  image: $CORE_IMAGE
  imagePullPolicy: Always
  imagePullSecrets:
  - registry-credentials
  logLevel: DEBUG
  telemetryExportInterval: 30000
  ultihashSecret:
    key: license
    name: ultihash
  securityContext:
    capabilities:
      add:
      - SYS_PTRACE
  policies: |
    {
      "Version": "2012-10-17",
      "Statement": {
         "Sid":  "AllowAllForAnybody",
         "Effect": "Allow",
         "Action": "*",
         "Principal": "*",
         "Resource": "*"
       }
    }

s3aTests:
  extraEnv:
    - name: GITHUB_PAT
      value: $GITHUB_PAT

etcd:
  replicaCount: 1
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02
  persistence:
    size: 5Gi
    storageClass: local-path

coordinator:
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02

entrypoint:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02
  
  ingress:
    enabled: false

deduplicator:
  replicas: 1
  storageClass: local-path
  storageSize: 2Gi
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02

database:
  primary:
    nodeSelector:
      kubernetes.io/hostname: opm-k8s-worker-02

    persistence:
      storageClass: local-path
      size: 2Gi

databaseInit:
  image: $DATABASE_INIT_IMAGE
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02

storage:
  groups:
    - id: 0
      type: ROUND_ROBIN
      storages: 1
      storageClass: local-path
      size: 5Gi
      mountPaths:
        - name: storage0
          containerPath: /var/lib/uh/storage
      nodeSelector:
        kubernetes.io/hostname: opm-k8s-worker-02

collector:
  config:
    exporters:
      otlphttp/uptrace:
        endpoint: http://opm-k8s-worker-04.ultihash.io
        headers:
          uptrace-dsn: http://${env:UH_EXPORTER_TOKEN}@opm-k8s-worker-04.ultihash.io
    receivers:
      kubeletstats: null
      prometheus: null
    service:
      pipelines:
        metrics:
          receivers:
          - otlp
  extraEnvs:
  - name: UH_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: UH_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UH_EXPORTER_TOKEN 
    valueFrom:
      secretKeyRef:
        name: ultihash
        key: token
  nodeSelector:
    kubernetes.io/hostname: opm-k8s-worker-02
  presets:
    kubeletMetrics:
      enabled: false

exporter:
  enabled: false