- name: Install UltiHash and all its pre-requisites
  hosts: localhost
  connection: local

  vars_prompt:
    - name: data_dir
      prompt: "Please enter a path where UltiHash may store its data:"
      private: no
      default: /var/lib/uh

  tasks:
    - name: Install required packages for Docker (Debian-family)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - software-properties-common
        - docker.io
        - docker-compose
      when: ansible_os_family == 'Debian'
      become: yes

    - name: Install required package for Docker (RedHat-family)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Install required package for Docker (SUSE-family)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker-compose
      when: ansible_os_family == "Suse"
      become: yes

    - name: Add Docker repository (RedHat-family)
      yum_repository:
        name: docker
        description: docker repository
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Install Docker (RedHat-family)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - docker-buildx-plugin
      when: ansible_os_family == "RedHat"
      become: yes

    - name: Starting and enabling docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Use Docker credentials for pulling private image
      command: docker pull ultihash/uh-data-node:latest
      register: pull_output
      no_log: true
      become: yes

    - name: Check if Docker pull was successful
      assert:
        that:
          - pull_output.rc == 0
        fail_msg: "Docker pull failed. Please check your private image name."
      become: no

    - name: Create a copy of docker-compose template
      command: cp docker-compose.yml.template docker-compose.yml
      args:
        creates: docker-compose.yml
      become: no

    - name: Adapt docker-compose configuration using the provided parameters
      replace:
        path: docker-compose.yml
        regexp: "{DATA_DIR}"
        replace: "{{ data_dir }}"
      become: no

    - name: Creates uh-data-node directory
      file:
        path: "{{ data_dir }}/uh-data-node"
        state: directory
        owner: "234"
        group: "234"
        mode: 0775
      become: yes

    - name: Creates grafana directory
      file:
        path: "{{ data_dir }}/grafana"
        state: directory
        owner: "472"
        group: "472"
      become: yes

    - name: Launch docker-compose (Debian-family)
      command: docker-compose up -d
      args:
        chdir: ./
      when: ansible_os_family == 'Debian'
      become: yes

    - name: Launch docker-compose (Other Linux Distributions)
      command: docker compose up -d
      args:
        chdir: ./
      when: ansible_os_family == "Suse" or ansible_os_family == "RedHat"
      become: yes

    - name: Installation summary
      ansible.builtin.debug:
        msg:
        - "UltiHash has been installed successfully and is accepting connections on port 21832."
        - "The service can be started manually by running 'docker-compose up -d'."
        - "The service can be stopped manually by running 'docker-compoose stop'."
        - "The metrics dashboard can be accessed at http://localhost:3000."


