apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stability-test-output
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stability-test-input
spec:
  capacity:
    storage: 1Gi # Ignored
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - allow-delete
    - region eu-central-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: ultihash-stability-test-corpora
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stability-test-input
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi # Ignored
  volumeName: stability-test-input