apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-test-input
  namespace: hdfs-parameterized-test
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-test-output
  namespace: hdfs-parameterized-test
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi