apiVersion: v1
kind: Pod
metadata:
  name: s3-data-downloader
spec:
  restartPolicy: Never
  nodeSelector:
    workload-type: tester
    purpose:  performance-testing-large
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  containers:
    - name: data-downloader
      image: amazon/aws-cli:latest
      args: ["s3", "sync", "s3://$S3_SOURCE_BUCKET", "/input"]
      env:
        - name: AWS_ACCESS_KEY_ID
          value: "$AWS_ACCESS_KEY_ID"
        - name: AWS_SECRET_ACCESS_KEY
          value: "$AWS_SECRET_ACCESS_KEY"
      volumeMounts:
        - mountPath: /input
          name: input
  volumes:
    - name: input
      persistentVolumeClaim:
        claimName: performance-test-input