apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: performance-test-output
spec:
  storageClassName: $TESTER_STORAGE_CLASS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $TESTER_VOLUME_SIZE
---
apiVersion: v1
kind: Pod
metadata:
  name: performance-tester
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: ghcr-registry-credentials
  nodeSelector:
    purpose:  parameterized-test-tester
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "testing"
      effect: "NoSchedule"
  containers:
    - name: performance-tester
      image: ghcr.io/ultihash/core-performance-test:latest
      imagePullPolicy: Always
      env:
        - name: TEST_TYPE
          value: UH_RANDOM_DATA
        - name: S3_ENDPOINT_URL
          value: "http://${RELEASE_NAME}-entrypoint:8080"
        - name: S3_DESTINATION_BUCKET
          value: random-test
        - name: READ_TIMEOUT
          value: "600"
        - name: JOBS
          value: "$TESTER_SCRIPT_JOBS"
        - name: MULTIPART_CHUNK_SIZE
          value: "67108864"
        - name: AMOUNT_GiB
          value: "$GENERATED_DATA_SIZE"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name:  "${RELEASE_NAME}-super-user-credentials"
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name:  "${RELEASE_NAME}-super-user-credentials"
              key: secret-key
      volumeMounts:
        - mountPath: /output
          name: output
  volumes:
    - name: output
      persistentVolumeClaim:
        claimName: performance-test-output