name: Basic PR checks

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - master

jobs:
    build-and-test:
        env:
            CXX: clang++
            CC: clang
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/stjank/uh-build-container/build:v1

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Cache ccache
              uses: actions/cache@v4
              with:
                  path: ~/.cache/ccache
                  key: ccache-${{ github.ref_name }}-${{ github.sha }}
                  restore-keys: |
                      ccache-${{ github.ref_name }}-
                      ccache-

            - name: Build
              run: |
                  cmake --preset default -DENABLE_CCACHE=ON
                  cmake --build build

            - name: Test
              run: ctest --test-dir build
