name: Basic PR checks

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        container:
            image: ubuntu:26.04

        steps:
            - name: Install Git
              run: apt update && apt install -y git

            - uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install dependencies
              run: |
                  apt update
                  apt install -y cmake clang ninja-build libpq-dev \
                    postgresql liblmdb++-dev protobuf-compiler-grpc \
                    libprotoc-dev libgrpc++-dev libgrpc-dev libboost-all-dev \
                    libstdc++-16-dev libicu-dev

            - name: Build
              run: |
                  cmake --preset default
                  cmake --build build

            - name: Test
              run: ctest --test-dir build
