name: Docker Build Template

on:
  workflow_call:
    inputs:
      docker_context:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      docker_build_args:
        required: false
        type: string
      docker_images:
        required: true
        type: string
      docker_tags:
        required: true
        type: string
      platforms:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true
      registry_token:
        required: true

jobs:

  docker-build:
    runs-on: heavyweight-generic-jobs
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ghcr_token }}
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to ghcr.io container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: plauth
        password: ${{ secrets.ghcr_token }}

    - name: Login to registry.ultihash.io container registry
      env: 
        registry_token: ${{ secrets.registry_token }}
      uses: docker/login-action@v2
      with:
        registry: registry.ultihash.io
        username: github
        password: ${{ secrets.registry_token }}

    - name: Docker metadata
      id: meta-release
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.docker_images }}
        tags: ${{ inputs.docker_tags }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile_path }} 
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta-release.outputs.tags }}
        labels: ${{ steps.meta-release.outputs.labels }}
        build-args: ${{ inputs.docker_build_args }}
        push: true
