name: Container Image CI

on:
  push:
    tags:
     - '*'

jobs:

  database-init:
    uses: ./.github/workflows/docker_build_template.yml 
    with:
      docker_context: .
      dockerfile_path: tools/database-init/Dockerfile
      docker_images: |
          registry.ultihash.io/stable/database-init
          ghcr.io/ultihash/database-init
      docker_tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      registry_token: ${{ secrets.REGISTRY_USER }}

  release:
    uses: ./.github/workflows/docker_build_template.yml 
    with:
      docker_context: .
      dockerfile_path: Dockerfile
      docker_images: |
          registry.ultihash.io/stable/core
          ghcr.io/ultihash/cluster
      docker_tags: |
          type=raw,value=latest
          type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      registry_token: ${{ secrets.REGISTRY_USER }}

  debug:
    uses: ./.github/workflows/docker_build_template.yml 
    with:
      docker_context: .
      dockerfile_path: Dockerfile
      docker_images: |
          ghcr.io/ultihash/cluster
      docker_tags: |
          type=raw,value=latest
          type=semver,suffix=-debug,pattern={{version}}
      docker_build_args: |
         BuildType=RelWithDebInfo
         DebugTools=True
      platforms: linux/amd64,linux/arm64
    secrets:
      ghcr_token: ${{ secrets.PAT }}