name: Feature Testing

on:
  workflow_dispatch:

jobs:

  build-core:
    uses: ./.github/workflows/docker_build_template.yml 
    with:
      docker_context: .
      dockerfile_path: Dockerfile
      docker_build_args: |
        BuildType=RelWithDebInfo
        DebugTools=True
      docker_images: registry.ultihash.io/dev/core
      docker_tags: "pr-${{ github.event.pull_request.number }}"
      platforms: linux/arm64
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      registry_token: ${{ secrets.REGISTRY_USER }}
        
  build-database-init:
    uses: ./.github/workflows/docker_build_template.yml
    with:
      docker_context: .
      dockerfile_path: tools/database-init/Dockerfile
      docker_images: registry.ultihash.io/dev/database-init
      docker_tags: "pr-${{ github.event.pull_request.number }}"
      platforms: linux/arm64
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      registry_token: ${{ secrets.REGISTRY_USER }}

  deploy-and-test:
    runs-on: lightweight-generic-jobs
    needs:
      - build-core
      - build-database-init
    strategy:
      matrix:
        test: 
          - name: simple-rr
            helm_values: testing/feature/helm-values-rr.yaml
          - name: simple-ec
            helm_values: testing/feature/helm-values-ec.yaml
    steps:

      - name: Define testing environment name
        run: |
          echo "ENVIRONMENT_NAME=pr-${{ github.event.pull_request.number }}-${{ matrix.test.name }}" >> $GITHUB_ENV
          echo "DOCKER_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core

      - uses: azure/setup-helm@v4.3.0

      - name: Generate Helm values
        uses: danielr1996/envsubst-action@1.1.0
        env:
          CORE_IMAGE: registry.ultihash.io/dev/core:${{ env.DOCKER_TAG }}
          DATABASE_INIT_IMAGE: registry.ultihash.io/dev/database-init:${{ env.DOCKER_TAG }}
        with:
          input: ${{ matrix.test.helm_values }}
          output: helm-values.yaml

      - name: Delete the testing environment if exists
        run: |
          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait --ignore-not-found
          kubectl delete pods -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete pvc -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete secrets -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete ns ${{ env.ENVIRONMENT_NAME }}
        continue-on-error: true

      - name: Install the Helm chart
        run: |
          kubectl create ns ${{ env.ENVIRONMENT_NAME }}
          kubectl create secret docker-registry registry-credentials -n ${{ env.ENVIRONMENT_NAME }} --docker-server='${{ vars.DOCKER_REGISTRY }}' --docker-username='${{ secrets.DOCKER_REGISTRY_USERNAME }}' --docker-password='${{ secrets.DOCKER_REGISTRY_PASSWORD }}'
          kubectl create secret generic ultihash -n ${{ env.ENVIRONMENT_NAME }} --from-literal=license='${{ secrets.UH_LICENSE_JSON }}' --from-literal=token='${{ secrets.MONITORING_TOKEN_ON_PREMISE }}'
          echo '${{ secrets.REGISTRY_USER }}' | helm registry login registry.ultihash.io -u github --password-stdin
          helm install ${{ env.ENVIRONMENT_NAME }} oci://registry.ultihash.io/stable/ultihash-cluster -n ${{ env.ENVIRONMENT_NAME }} --values helm-values.yaml --wait --timeout 60m

      - name: Run feature tests
        run: |
          helm test ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --filter name=${{ env.ENVIRONMENT_NAME }}-feature-tests --logs --timeout 20m

  cleanup:
    runs-on: lightweight-generic-jobs
    needs: deploy-and-test
    if: ${{ always() }}
    strategy:
      matrix:
        test:
          - name: simple-rr
          - name: simple-ec
    steps:

      - name: Define testing environment name
        run: |
          echo "ENVIRONMENT_NAME=pr-${{ github.event.pull_request.number }}-${{ matrix.test.name }}" >> $GITHUB_ENV
          echo "DOCKER_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core

      - uses: azure/setup-helm@v4.3.0

      - name: Environment cleanup
        run: |
          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait
          kubectl delete pods -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete pvc -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete secrets -n ${{ env.ENVIRONMENT_NAME }} --all --force
          kubectl delete ns ${{ env.ENVIRONMENT_NAME }}
        continue-on-error: true
