name: HDFS Parameterized Performance Test

env:
  ENVIRONMENT_NAME: hdfs-parameterized-test

on:
  workflow_dispatch:
    inputs:
      hdfs_block_size:
        description: "Block size of HDFS in Bytes"
        default: "67108864" # 64 MiB
      ec2_instance_type:
        description: 'Type of the used EC2 instance to host HDFS cluster'
        default: 'r6a.4xlarge'
      ec2_instance_count:
        description: 'Number of deployed EC2 instances'
        default: 1
      storage_volume_size:
        description: 'Volume size provisioned PER datanode'
        default: '100Gi'
      hdfs_storage_class:
        description: 'Storage class used by the HDFS cluster'
        default: 'ebs-csi-gp2'
      tester_ec2_instance_type:
        description: 'Type of the used EC2 instance to host the test script'
        default: 'c6id.8xlarge'
      test_file_count:
        description: "Number of files in the test dataset. Dataset size = test_file_count * test_file_size"
        default: 500
      test_file_size:
        description: "File size for all files in the test data set (in MiB)"
        default: 64
      test_thread_count:
        description: "Number of threads to upload/download the dataset"
        default: 10
      test_queue_size:
        description: "The queue size for the dataset upload/download"
        default: 20

jobs:

  deploy-and-test:
    runs-on: lightweight-generic-jobs
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}  
      
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core
    
      - uses: azure/setup-helm@v4.3.0

      - name: Generate the Karpenter node pools
        uses: danielr1996/envsubst-action@1.1.0
        env:
          EC2_INSTANCE_TYPE: "${{ github.event.inputs.ec2_instance_type }}"
          TESTER_EC2_INSTANCE_TYPE: "${{ github.event.inputs.tester_ec2_instance_type }}"
        with:
          input: testing/performance/hdfs/karpenter-node-pools.yaml
          output: karpenter-node-pools.yaml

      - name: Generate Helm values
        uses: danielr1996/envsubst-action@1.1.0
        env:
          HDFS_BLOCK_SIZE: "${{ github.event.inputs.hdfs_block_size }}"
          TEST_FILE_COUNT: "${{ github.event.inputs.test_file_count }}"
          TEST_THREAD_COUNT: "${{ github.event.inputs.test_thread_count }}"
          TEST_QUEUE_SIZE: "${{ github.event.inputs.test_queue_size }}"
          EC2_INSTANCE_COUNT: "${{ github.event.inputs.ec2_instance_count }}"
          HDFS_STORAGE_CLASS: "${{ github.event.inputs.hdfs_storage_class }}"
          STORAGE_VOLUME_SIZE: "${{ github.event.inputs.storage_volume_size }}"
          TEST_FILE_SIZE: "${{ github.event.inputs.test_file_size }}"
        with:
          input: testing/performance/hdfs/hdfs-helm-values.yaml
          output: helm-values.yaml

      - name: Provision the testing environment
        run: |
          kubectl create ns ${{ env.ENVIRONMENT_NAME }}
          kubectl apply -f karpenter-node-pools.yaml
          kubectl apply -f testing/performance/hdfs/tester-volumes.yaml

      - name: Install the HDFS cluster
        run: |
          echo '${{ secrets.REGISTRY_USER }}' | helm registry login registry.ultihash.io -u github --password-stdin
          helm install ${{ env.ENVIRONMENT_NAME }} oci://registry.ultihash.io/staging/hdfs -n ${{ env.ENVIRONMENT_NAME }} --values helm-values.yaml --wait --timeout 60m
          sleep 120
      
      - name: Execute performance test against HDFS
        run: |
          helm test ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --filter name=${{ env.ENVIRONMENT_NAME }}-performance-test --logs --timeout 3h

  cleanup:
    runs-on: lightweight-generic-jobs
    needs: deploy-and-test
    if: ${{ always() }}
    steps:

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core
    
      - uses: azure/setup-helm@v4.3.0

      - name: Environment cleanup
        run: |
          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait || true
          kubectl delete pods --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
          kubectl delete pvc --all -n ${{ env.ENVIRONMENT_NAME }}
          kubectl delete ns ${{ env.ENVIRONMENT_NAME }} || true
          kubectl delete nodepool parameterized-test-hdfs hdfs-parameterized-test-tester || true
