name: Integration Test (C++ Apps)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  integration-test-docker:
    runs-on: docker-image-builder

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: plauth
          password: ${{ secrets.PAT }}

      - name: Running integration tests
        working-directory: ${{github.workspace}}/testing
        run: ./start-e2e.sh

      - name: Upload working directory of failed run
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: workspace
          path: ${{github.workspace}}
          retention-days: 1
