name: Small-Sized Performance Testing AWS

on:
  workflow_call:
    inputs:
      env_name:         
        required: true
        type: string
      docker_image_tag: 
        required: true
        type: string
      docker_registry:
        required: true
        type: string
      helm_values:
        required: true
        type: string
      storage_group_type:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true
      registry_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      uh_license:
        required: true
      monitoring_token:
        required: true

jobs:

  deploy-and-test:
    runs-on: lightweight-generic-jobs
    steps:

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ghcr_token }}
      
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.aws_access_key_id }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core
    
      - uses: azure/setup-helm@v4.3.0

      - name: Delete the testing environment if exists
        run: |
          helm uninstall ${{ inputs.env_name }} -n ${{ inputs.env_name }} --wait --ignore-not-found || true
          kubectl delete pods --all --force -n ${{ inputs.env_name }} || true
          kubectl delete pvc --all -n ${{ inputs.env_name }}
          kubectl delete secrets --all -n ${{ inputs.env_name }} || true
          kubectl delete ns ${{ inputs.env_name }} || true
        continue-on-error: true
      
      - name: Provision the testing environment
        run: |
          kubectl create ns ${{ inputs.env_name }}
          kubectl create secret docker-registry registry-credentials -n ${{ inputs.env_name }} --docker-server='${{ vars.docker_registry }}' --docker-username='${{ secrets.docker_registry_username }}' --docker-password='${{ secrets.docker_registry_password }}'
          kubectl create secret generic ultihash -n ${{ inputs.env_name }} --from-literal=license='${{ secrets.uh_license }}' --from-literal=token='${{ secrets.monitoring_token }}'

      - name: Generate the performance tester manifest for UltiHash
        uses: danielr1996/envsubst-action@1.1.0
        env:
          TEST_NAME: "small_performance_test_ultihash"
          AMOUNT_GiB: "100"
          PROM_URL: "prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091"
          TEST_TYPE: UH
          S3_ENDPOINT_URL: "http://${{ inputs.env_name }}-entrypoint:8080"
          S3_SOURCE_BUCKET: test
          S3_DESTINATION_BUCKET: test
          RELEASE_NAME: ${{ inputs.env_name }}
          READ_TIMEOUT: "600"
          JOBS: "4"
          STORAGE_GROUP_TYPE: ${{ inputs.storage_group_type }}
        with:
          input: testing/performance/small/performance-tester.yaml
          output: performance-tester-ultihash.yaml

      - name: Generate Helm values for UltiHash
        uses: danielr1996/envsubst-action@1.1.0
        env:
          CORE_IMAGE: registry.ultihash.io/dev/core:${{ inputs.docker_image_tag }}
          DATABASE_INIT_IMAGE: registry.ultihash.io/dev/database-init:${{ inputs.docker_image_tag }}
        with:
          input: ${{ inputs.helm_values }}
          output: ultihash-helm-values.yaml
          
      - name: Install the UltiHash cluster
        run: |
          echo '${{ secrets.registry_token }}' | helm registry login registry.ultihash.io -u github --password-stdin
          helm install ${{ inputs.env_name }} oci://registry.ultihash.io/stable/ultihash-cluster -n ${{ inputs.env_name }} --values ultihash-helm-values.yaml --wait --timeout 60m

      - name: Execute the performance test against UltiHash
        run: |
          bash testing/performance/execute_job.sh performance-tester-ultihash.yaml performance-tester ${{ inputs.env_name }} 3h
 
  cleanup:
    runs-on: lightweight-generic-jobs
    needs: deploy-and-test
    if: ${{ always() }}
    steps:

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.aws_access_key_id }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.aws_secret_access_key }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - uses: azure/setup-kubectl@v4

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          aws eks update-kubeconfig --name aws-core
    
      - uses: azure/setup-helm@v4.3.0

      - name: Environment cleanup
        run: |
          helm uninstall ${{ inputs.env_name }} -n ${{ inputs.env_name }} --wait || true
          kubectl delete pods --all --force -n ${{ inputs.env_name }} || true
          kubectl delete pvc --all -n ${{ inputs.env_name }}
          kubectl delete secrets --all -n ${{ inputs.env_name }} || true
          kubectl delete ns ${{ inputs.env_name }} || true
        continue-on-error: true
      