name: PySpark Testing On Premise

on:
  workflow_call:
    inputs:
      env_name:         
        required: true
        type: string
      docker_image_tag: 
        required: true
        type: string
      docker_registry:
        required: true
        type: string
    secrets:
      ghcr_token:
        required: true
      docker_registry_username:
        required: true
      docker_registry_password:
        required: true
      registry_token:
        required: true
      kubeconfig:
        required: true
      uh_license:
        required: true
      monitoring_token:
        required: true

jobs:

  deploy-and-test:
    runs-on: lightweight-generic-jobs
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ghcr_token }}

      - uses: azure/setup-kubectl@v3
        with:
          version: v1.28.7

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          echo '${{ secrets.kubeconfig }}' > ~/.kube/config

      - uses: azure/setup-helm@v4.0.0
        with:
         version: v3.14.0

      - name: Generate Helm values
        uses: danielr1996/envsubst-action@1.0.0
        env:
          CORE_IMAGE: ghcr.io/ultihash/cluster:${{ inputs.docker_image_tag }}
          DATABASE_INIT_IMAGE: ghcr.io/ultihash/database-init:${{ inputs.docker_image_tag }}
          BUCKET_NAME: datasets
        with:
          input: testing/pyspark/helm-values-on-premise.yaml
          output: helm-values.yaml

      - name: Delete the testing environment if exists
        run: |
          helm uninstall ${{ inputs.env_name }} -n ${{ inputs.env_name }} --wait
          kubectl delete pvc -n ${{ inputs.env_name }} --all
          kubectl delete secrets -n ${{ inputs.env_name }} --all --force
          kubectl delete ns ${{ inputs.env_name }}
        continue-on-error: true

      - name: Install the Helm chart
        run: |
          kubectl create ns ${{ inputs.env_name }}
          kubectl create secret docker-registry registry-credentials -n ${{ inputs.env_name }} --docker-server='${{ inputs.docker_registry }}' --docker-username='${{ secrets.docker_registry_username }}' --docker-password='${{ secrets.docker_registry_password }}'
          kubectl create secret generic ultihash -n ${{ inputs.env_name }} --from-literal=license='${{ secrets.uh_license }}' --from-literal=token='${{ secrets.monitoring_token }}'
          echo '${{ secrets.registry_token }}' | helm registry login registry.ultihash.io -u github --password-stdin
          helm install ${{ inputs.env_name }} oci://registry.ultihash.io/stable/ultihash-cluster -n ${{ inputs.env_name }} --values helm-values.yaml --wait --timeout 15m

      - name: Run PySpark test
        run: |
          helm test ${{ inputs.env_name }} -n ${{ inputs.env_name }} --filter name=${{ inputs.env_name }}-pyspark-test --logs --timeout 1h

  cleanup:
    runs-on: lightweight-generic-jobs
    needs: deploy-and-test
    if: ${{ always() }}
    steps:

      - uses: azure/setup-kubectl@v3
        with:
          version: v1.28.7

      - name: Download Kubeconfig
        run: |
          mkdir ~/.kube
          echo '${{ secrets.kubeconfig }}' > ~/.kube/config
    
      - uses: azure/setup-helm@v4.0.0
        with:
         version: v3.14.0

      - name: Environment cleanup
        run: |
          helm uninstall ${{ inputs.env_name }} -n ${{ inputs.env_name }} --wait
          kubectl delete pods -n ${{ inputs.env_name }} --all --force
          kubectl delete pvc -n ${{ inputs.env_name }} --all
          kubectl delete secrets -n ${{ inputs.env_name }} --all --force
          kubectl delete ns ${{ inputs.env_name }}
        continue-on-error: true