name: Unit Tests (Linux, GCC, aarch64)

on:
  schedule:
    - cron: '0 0 * * MON-FRI'
  workflow_dispatch:
  
jobs:

  provision-aarch64-runner:
    runs-on: lightweight-generic-jobs
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: amd64

      - name: Setup the AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

      - name: Provision runner instance
        run: | 
          aws ec2 run-instances \
            --count 1 \
            --image-id ${{ vars.AARCH64_RUNNER_AMI }} \
            --instance-type r8g.2xlarge \
            --key-name aarch64-github-runner \
            --security-group-ids sg-050ac7da1ac46a7c8 \
            --subnet-id subnet-01f6973461a5a7a5d \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=aarch64-github-runner}]' \
            --instance-initiated-shutdown-behavior terminate \
            --associate-public-ip-address \
            --region eu-central-1 \
            --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":50}}]'
    
  unit-gcc-aarch64-linux:
    strategy:
      matrix:
        build: [Release, Debug]
    runs-on: heavyweight-core-aarch64-jobs
    needs: provision-aarch64-runner

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Configure CMake
        run: CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TOOLS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build }} --parallel $(nproc)

      - name: Test
        env:
          ETCDCTL_API: 3
        working-directory: ${{github.workspace}}/build
        run: |
          etcd&
          sleep 5
          etcdctl del "" --from-key=true
          ctest -C ${{ matrix.build }} --output-on-failure
          etcdctl del "" --from-key=true
