name: Unit Tests TSAN (Linux, clang, x86_64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  unit-tsan-x86_64-linux:
    if: false
    strategy:
      matrix:
        build: [RelWithDebInfo]
    runs-on: heavyweight-core-x86-64-jobs

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Configure CMake
        env:
          CC: /usr/bin/clang-18
          CXX: /usr/bin/clang++-18
        run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TOOLS=OFF -DENABLE_TSAN=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build }} --parallel $(nproc)

      - name: Test
        env:
          ETCDCTL_API: 3
          TSAN_OPTIONS: detect_odr_violation=0,suppressions=${{github.workspace}}/tsan-suppressions
        working-directory: ${{github.workspace}}/build
        run: |
          etcd&
          sleep 5
          etcdctl del "" --from-key=true
          ctest -C ${{ matrix.build }} --output-on-failure
          etcdctl del "" --from-key=true

