name: Unit Tests (Linux, GCC, aarch64)

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  unit-gcc-aarch64-linux:
    strategy:
      matrix:
        build: [Release, Debug]
    runs-on: uh-aarch64-ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TOOLS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build }} --parallel $(nproc)

      - name: Test
        env:
          ETCDCTL_API: 3
        working-directory: ${{github.workspace}}/build
        run: |
          etcd&
          sleep 5
          etcdctl del "" --from-key=true
          ctest -C ${{ matrix.build }} --output-on-failure
          etcdctl del "" --from-key=true
