name: Unit Tests (Linux, GCC, x86_64)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  unit-gcc-x86_64-linux:
    strategy:
      matrix:
        build: [Release, Debug]
    runs-on: heavyweight-core-x86-64-jobs

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Set the license
        run: echo "UH_LICENSE_JSON=${{ secrets.UH_LICENSE_JSON }}" >> $GITHUB_ENV

      - name: Configure CMake
        run: CC=/usr/bin/gcc CXX=/usr/bin/g++ cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TOOLS=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build }} --parallel $(nproc)

      - name: Test
        env:
          ETCDCTL_API: 3
        working-directory: ${{github.workspace}}/build
        run: |
          etcd&
          sleep 5
          etcdctl del "" --from-key=true
          ctest -C ${{ matrix.build }} --output-on-failure
          etcdctl del "" --from-key=true

