name: Unit Tests UBSAN (clang)

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:

  unit-ubsan:
    strategy:
      matrix:
        target: [RelWithDebInfo]
    uses: ./.github/workflows/unit_testing_workflow.yml
    with: 
       target: ${{ matrix.target }}
       runs_on: heavyweight-core-aarch64-jobs
       cmake_env: >
        {
          "CC": "/usr/bin/clang-18",
          "CXX": "/usr/bin/clang++-18"
        }
       cmake_additional_args: -DENABLE_UBSAN=ON
       test_env: >
        {
          "ETCDCTL_API": "3",
          "ASAN_OPTIONS": "detect_odr_violation=0"
        }
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      uh_license: ${{ secrets.UH_LICENSE_JSON }}

