name: Unit Tests (GCC)

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  unit-gcc:
    strategy:
      matrix:
        target: [Release, Debug]
    uses: ./.github/workflows/unit_testing_workflow.yml
    with: 
       target: ${{ matrix.target }}
       runs_on: heavyweight-core-aarch64-jobs
       cmake_env: >
        {
          "CC": "/usr/bin/gcc",
          "CXX": "/usr/bin/g++"
        }
       test_env: >
        {
          "ETCDCTL_API": "3"
        }
    secrets:
      ghcr_token: ${{ secrets.PAT }}
      uh_license: ${{ secrets.UH_LICENSE_JSON }}

